name: Build and Test GBTNetwork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v -o gbtnode main.go

      - name: Run basic test
        run: |
          ./gbtnode &
          sleep 5
          curl -f http://localhost:9636 || exit 1
